# Site settings
title: Donut UX
email: contact@donutux.la
url: http://donutux.la
description: "Established in 2014, two girls from a rough town discover a shared love of technology and the desire to help the little guy. Donut UX was born."

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary-dark: '#F0F0F0'
  primary-dark: '#FFF'
  links: '#219ab3'

# Footer settings
footer: donutux.la

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter (jackie)
    url: https://twitter.com/iamjackietanner
  - title: twitter (alicia)
    url: https://twitter.com/AliciaJOlivares

# Build settings
markdown: kramdown
permalink: pretty
